### ISSUE TITLE
Precision is always 0

### ISSUE THREAD

**Issue by Wallace-222** [thuml/PADA#3]
I follow the command to run the code (data list are right), however, the precision is always 0. What's the possible reason? @caozhangjie @MaLijia-thss15

**Comment by youkaichao** [comment]
please check https://github.com/thuml/Xlearn/commit/2dfdba2c61ffe2c55cab238b8a36c831e3c21f94

**Comment by sunxirui310** [comment]
> please check [thuml/Xlearn@2dfdba2](https://github.com/thuml/Xlearn/commit/2dfdba2c61ffe2c55cab238b8a36c831e3c21f94)

i'm facing the same problem. thanks

**Comment by youkaichao** [comment]
@sunxirui310  does it help?

**Comment by sunxirui310** [comment]
yeah.
![image](https://user-images.githubusercontent.com/19179730/56281496-5cd7ef00-613f-11e9-875c-149861d92ce8.png)

**Comment by caozhangjie** [comment]
What's your PyTorch version?

**Comment by caozhangjie** [comment]
We use PyTorch version 0.3.1 in our code.

**Comment by miaomiao9720** [comment]
sorry, I according to the webpage input “.item()”
but  AttributeError: 'int' object has no attribute 'item'
type(torch.sum(torch.squeeze(predict).float() == all_label))
<class 'int'>

**Comment by caozhangjie** [comment]
Pytorch 0.3.1 can reproduce the results well. Pytorch 0.4.0 with ,item() can solve the zero precision problem but the results are not good. In Pytorch 0.3.1, there is no .item() needed
