### ISSUE TITLE
the coefficient scheduler for gradient reversal module

### ISSUE THREAD

**Issue by cmhungsteve** [thuml/PADA#4]
`self.coeff = np.float(2.0 * (self.high - self.low) / (1.0 + np.exp(-self.alpha*self.iter_num / self.max_iter)) - (self.high - self.low) + self.low)`
Is the `max_iter` always set as 10000?
From the DANN paper, I thought it depends on the total iteration number during training.
Is there any reason to use a fixed number?

Thank you.

**Comment by caozhangjie** [comment]
I write this code according to the caffe code of DANN

**Comment by cmhungsteve** [comment]
I see. Thank you.
I just found lots of public implementation of DANN.
Most of them use the total training iteration number, but all the repositories in your lab use a fixed number (e.g. 10000).

Since your lab has published lots of Domain Adaptation papers in top conferences, I just wonder if it's one of the important tricks to have good results for DA training.

**Comment by caozhangjie** [comment]
This number will influence the convergence speed, but it is not sensitive.

**Comment by cmhungsteve** [comment]
Got it. Thank you so much.
