### ISSUE TITLE
class weight

### ISSUE THREAD

**Issue by cmhungsteve** [thuml/PADA#5]
In the paper, the class weight seems like a probability distribution (output of Softmax), but in your implementation, the class weight seems like the output from a fully-connected layer. 
Is there any reason why the implementation is different from the paper?

Thank you.

**Comment by caozhangjie** [comment]
We add softmax before using the weight. Please check line 280 in train_pada.py.

**Comment by cmhungsteve** [comment]
Got it. Thank you.
