### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by Dr-Zhou** [thuml/PADA#7]
![image](https://user-images.githubusercontent.com/26479520/60947184-852c4f80-a322-11e9-8744-f3b4acc922b5.png)
![image](https://user-images.githubusercontent.com/26479520/60947214-99704c80-a322-11e9-99f7-dc5d625266f1.png)
This is my path and file location.but I don't find the problem.

**Comment by caozhangjiex** [comment]
I mean you need to modify the list file in data/. The path in the list file now is my local path.

**Comment by Dr-Zhou** [comment]
ok。I understand it。thank you。 I will try it。
