### ISSUE TITLE
the test file is missing. 

### ISSUE THREAD

**Issue by S-Choudhuri** [thuml/PADA#8]
Python file for testing the datasets is missing from the src folder

**Comment by caozhangjie** [comment]
For convenience, the test process is embedded into training. We first select hyper-parameter with cross-validation and then train the model and test simultaneously.

**Comment by S-Choudhuri** [comment]
Thanks for the quick response. I am actually confused with a single precision value saved in the log file. For office dataset, there should be 6 accuracy scores (one for each task). Is the code saving the task-specific accuracies somewhere?

**Comment by caozhangjie** [comment]
I only run one task per run. Please see the instructions to switch between tasks.
